name: Build hapticslib dll pre-release
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_release:
    name: Build dll and add to pre-release in releases
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - i686-pc-windows-msvc
        toolchain:
          - stable
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Rustup update and add toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup target add ${{ matrix.target }}

      - name: Build release version
        run: cargo build --release --verbose

      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          files: |
            ./target/i686-pc-windows-msvc/release/hapticslib.dll
          args: -9fq

      - name: Create Pre-Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: ./target/i686-pc-windows-msvc/release/hapticslib.dll
          name: "Hapticslib Pre-Release v0.1.0-rc${{ github.run_number }}"
          prerelease: true
          tag: "v0.1.0-rc${{ github.run_number }}"
