name: Build hapticslib dll pre-release
on: [push, workflow_dispatch]
jobs:
  build_and_release:
    name: Build dll and add to pre-release in releases
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - i686-pc-windows-msvc
        toolchain:
          - stable
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Rustup update and add toolchain
        run: rustup update ${{ matrix.toolchain }} && rustup target add ${{ matrix.target }}

      - name: Build release version
        run: cargo build --release --verbose

      - name: Create Pre-Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifact: ./target/i686-pc-windows-msvc/release/hapticslib.dll
          commit: true
          name: "Hapticslib Pre-Release ${{ github.sha }}"
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}



        